---
baseurl:            http://ksmigiel.com/
metadataformat: "yaml"
permalinks:
  post: /:year/:month/:slug

params:
  inc:
    # Blog Information
    title:        "Krzysztof Śmigiel | Blog"
    subtitle:     "Programowanie i data science"
    cover_image:  blog-cover.jpg
    
    github:       ksmigiel
    twitter:      k_smigiel
    about_link:   /about
    
    # Comments
    disqus:
      # Set a shortname to enable disqus comments
      shortname:  ksmigiel
    
    # Sharing settings
    sharing:
      twitter:    true
      facebook:   true
      gplus:      false
      hn:         false
      
   # Analytics     
    analytics:
      googleid: UA-58701947-1
